env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
jobs:
  build:
    if: ${{ needs.check_duplicate.outputs.should_skip != 'true' || github.ref == 'refs/heads/master'
      }}
    needs: check_duplicate
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: ${{ matrix.containers }}
      name: Start test databases
      run: 'docker-compose up --detach ${{ matrix.containers }} &&\

        time docker-compose up block-until-healthy &&\

        docker ps

        '
    - continue-on-error: true
      name: Initialize cache
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Run tests
      run: mvn --batch-mode install -am jacoco:report --activate-profiles all,travis,examples
        -Duser.timezone=UTC
    - continue-on-error: true
      if: failure()
      name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Report coverage
      run: mvn --batch-mode coveralls:report --activate-profiles all,travis
    - continue-on-error: true
      env:
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: "Deploy snapshot \U0001F680"
      run: mvn --batch-mode clean deploy --settings deploy/.m2/settings.xml -DskipTests
    - continue-on-error: true
      name: Clean up before caching
      run: rm -rf ~/.m2/repository/com/querydsl/
    strategy:
      matrix:
        include:
        - containers: db2 mysql postgresql mongo sqlserver oracle cubrid firebird
          target: test
        java:
        - 1.8
        - 11
        - 17
        - 21
        target:
        - test
  check_duplicate:
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        concurrent_skipping: same_content_newer
name: querydsl
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
